name: deploy_to_firebase_hosting

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: github.repository == 'valueourminds/website'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install npm dependencies
      run: npm install

    - name: Build static files
      run: npm run build

    - name: Deploy to Firebase Hosting
      run: npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
